language: generic

os: linux

jobs:
  fast_finish: true
  include:
    - env:
      - PYTHON=2.7

    - env:
      - PYTHON=3.4

    - env:
      - PYTHON=3.5

    - env:
      - PYTHON=3.6

    - env:
      - PYTHON=3.6
      os: osx

install:
    - source ci/install.sh;

script:
    - pytest --cov=pyunfold pyunfold
    - flake8 pyunfold
    # Only test that documentation builds on Python 3.6
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
        bash ci/build_docs.sh;
      fi

after_success:
    - pip install codecov
    - codecov

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs/_build/html
    target_branch: gh-pages
    email: "github-pages-deploy@travis-ci.org"
    on:
        branch: master
        condition: $PYTHON = 3.6 && $TRAVIS_OS_NAME = linux
