name: pyunfold_dev
channels:
  - conda-forge
  - nlesc
dependencies:
  # Analysis requirements
  - numpy
  - scipy
  - pandas
  - matplotlib
  - root5
  - root-numpy
  # Testing requirements
  - pytest
  - flake8
  # Documentation requirements
  - sphinx
  - numpydoc
  - sphinx_rtd_theme
