name: pyunfold_dev
channels:
  - conda-forge
dependencies:
  # Analysis requirements
  - numpy
  - scipy
  - pandas
  - six
  # Testing requirements
  - pytest
  - flake8
  - pytables
  # Documentation requirements
  - sphinx
  - numpydoc
  - sphinx_rtd_theme
  - nbsphinx
  - jupyter
  - matplotlib
  - seaborn
